### ISSUE TITLE
Failed to build in windows

### ISSUE THREAD

**Issue by alisonrag** [zhad3/zrenderer#15]
OS: Windows 10 PRO
Visual Studio: 2022 Community
DUB version 1.27.0, built on Dec 19 2021

executed command in Developer Console:
`dub build :server`

error: 
```
source\linearalgebra\operations.d(290,23): Error: `pure` function `linearalgebra.operations.apply!(round).apply` cannot call impure function `std.math.rounding.round`
source\linearalgebra\operations.d(290,38): Error: `pure` function `linearalgebra.operations.apply!(round).apply` cannot call impure function `std.math.rounding.round`
source\linearalgebra\transform.d(56,99): Error: template instance `linearalgebra.operations.apply!(round)` error instantiating
source\linearalgebra\operations.d(295,23): Error: `pure` function `linearalgebra.operations.apply!(round).apply` cannot call impure function `std.math.rounding.round`
source\linearalgebra\operations.d(295,38): Error: `pure` function `linearalgebra.operations.apply!(round).apply` cannot call impure function `std.math.rounding.round`
source\linearalgebra\operations.d(295,53): Error: `pure` function `linearalgebra.operations.apply!(round).apply` cannot call impure function `std.math.rounding.round`
source\renderer.d(59,39): Error: template instance `linearalgebra.operations.apply!(round)` error instantiating
C:\D\dmd2\windows\bin\dmd.exe failed with exit code 1.
```

screenshot:
![image](https://user-images.githubusercontent.com/10372732/150658899-a5cb67a7-5313-411c-9c9b-c782211e0821.png)

**Comment by zhad3** [comment]
Yeah, I am currently not using the newest version of DMD or LDC where this check does not seem to be performed. Either that or the round functions signature changed. I am using LDC2 1.26.0 which would be the equivalent of DMD v2.096.1.

I'll try the latest version on Windows and see if there are more than just the issues in your post when I have time.

**Comment by zhad3** [comment]
@alisonrag I have committed a change that should fix this. I recommend using the LDC2 compiler though as I have had trouble with DMD myself. I also updated the README accordingly that shows the build command using LDC2.

**Comment by alisonrag** [comment]
i think i messed something related to visual studio / compiler
![image](https://user-images.githubusercontent.com/10372732/151670372-2ea5ece8-d951-49f3-a52c-21c1ae7ded0c.png)

i will try a clean installation later but thanks for the update <3

**Comment by zhad3** [comment]
It says there:
`warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'`
It seems you have started the visual studio developer console for x86 instead of x64.

**Comment by alisonrag** [comment]
same error
![image](https://user-images.githubusercontent.com/10372732/151671587-aeeca865-a765-4ab3-a793-7ff18d2ed380.png)

i will try to uninstall everything and re-install

**Comment by zhad3** [comment]
Interesting. Can you try to add `--force`. That will recompile everything, also the dependencies.

**Comment by alisonrag** [comment]
uninstalled everything, cleaned left folders ( included C:\Users\User\AppData\Local\dub)

installed:
Visual Studio 2019 and Build Tools to VS 2019
ldc2-1.28.1-windows-multilib (in installation selected only x64 lib)
added `C:\Program Files\LDC 1.28\lib64` to path. (ldc2 installer doesn't add)

opened:
`x64 Native Tools Command Prompt for VS 2019`

executed the following commands:
`dub build --compiler=ldc2 --build=release --force :server`
`dub build --compiler=ldc2 --build=release --force :cli`

and it is working
CLI:
![image](https://user-images.githubusercontent.com/10372732/151673047-c273c454-f029-48d6-8ca7-0a577453697e.png)

server:
![image](https://user-images.githubusercontent.com/10372732/151673059-d637cc41-4df9-4a28-aa14-75269e1745ec.png)

result:
![image](https://user-images.githubusercontent.com/10372732/151673071-7587b896-475b-4ea1-93ab-7cf826aec16d.png)

**Comment by alisonrag** [comment]
thanks for the help and congratulations for this awesome project
