### ISSUE TITLE
Garment rendered wrong  in front of body in some frames

### ISSUE THREAD

**Issue by alisonrag** [zhad3/zrenderer#16]
this seems to happen in the following actions: 0 (idle), 16(sit), 72(freeze2)
request example:
```
{
    "job": ["4063"],
    "action": 16,
    "head": 21,
    "headPalette": 6,
    "headgear": [1985,1309,572],
    "gender": 0,
    "garment": 48,
    "bodyPalette": 3
}
```

result:
![idle](https://user-images.githubusercontent.com/10372732/150659058-f3037b4d-d755-4f06-ae60-70d63181eb38.png)

![sit](https://user-images.githubusercontent.com/10372732/150659064-2c20a1e8-9969-484f-af2f-1ac35a651d70.png)

**Comment by zhad3** [comment]
Thank your for reporting, I was able to reproduce this. The cause seems to lie in the depth sorting when an animated headgear is in use.

**Comment by zhad3** [comment]
Actions such as Freeze need to be special treated e.g. by using only the first frame ignoring all headgears. There are probably some other actions that also only have 1 frame. That is something I'll look at some point.

**Comment by alisonrag** [comment]
Fixed at:
idle (0~7) and sit (16~23)

![idle](https://user-images.githubusercontent.com/10372732/150688801-7b9a65a0-f885-4940-9ff9-874723c37302.png)
![sit](https://user-images.githubusercontent.com/10372732/150688802-304938c7-396d-452d-a487-a6a3050b663a.png)

**Comment by zhad3** [comment]
Created a follow-up ticket here: #18
