### ISSUE TITLE
Failed to find .spr for garments

### ISSUE THREAD

**Issue by alisonrag** [zhad3/zrenderer#17]
zrenderer can't find some garments .spr files

this is because in some cases gravity only add 1 .spr file and it is located in the root of item folder:
![image](https://user-images.githubusercontent.com/10372732/150659383-4be2ce5f-d4c8-4316-bfe6-fc17480ffbc0.png)

request example:
```
{
    "job": ["4063"],
    "action": 96,
    "head": 21,
    "headPalette": 6,
    "headgear": [1985,1309,572],
    "gender": 0,
    "garment": 107,
    "bodyPalette": 3
}
```

result:
![image](https://user-images.githubusercontent.com/10372732/150659344-3c276cce-1a5e-4a99-b65e-b712725f4f59.png)
![garment](https://user-images.githubusercontent.com/10372732/150659349-d8d108a6-42db-45c8-80cb-566ecda1ccef.png)

zrenderer should also check for .spr in: `sprite/로브/item_folder/`

**Comment by zhad3** [comment]
Thank you for reporting. Is this something the new clients are doing? I haven't yet gotten the 2021 clients working with rAthena and on my 2018 client it doesn't show the garment unless the corresponding spr name exists for the job.

**Comment by alisonrag** [comment]
seems fixed, thanks for your attention and time.
![garment](https://user-images.githubusercontent.com/10372732/150688403-3e785436-612d-47fc-b39f-ea3deef69017.png)

sorry, i don't know since from when it started to use only 1 .spr file, i discovered because i was facing the same issue in another project:
https://github.com/Balferian/ROChargenPHP/pull/1/commits/a12c23d6f1495668810170c9753f4f4ab04a946e
