### ISSUE TITLE
Ubuntu - zrenderer release version not generating image

### ISSUE THREAD

**Issue by alisonrag** [zhad3/zrenderer#21]
In Ubuntu, server mode is not generating image when use the compiled release version

using debug:
![image](https://user-images.githubusercontent.com/10372732/158043307-a7f9bca9-32a0-4eff-81f3-5437931dbdbc.png)

output folder:
![image](https://user-images.githubusercontent.com/10372732/158043380-1877b13a-7e22-42eb-855a-f6e153741d5d.png)

-------------
using `--build=release`
![image](https://user-images.githubusercontent.com/10372732/158043333-b0a7f369-92ab-4f70-aa54-8817b21c2943.png)

output folder: 
![image](https://user-images.githubusercontent.com/10372732/158043352-d271e208-041b-4915-b1b1-c42693d226e7.png)

**Comment by zhad3** [comment]
@alisonrag, could you provide some more information? I can not reproduce this issue.

Is the server printing any logs?

Does it work in the CLI version using the `release` build?

What compiler versions are you using?
`$ dub --version`
`$ ldc2 --version` or `$ dmd --version`

Are there any warnings during compilation?

**Comment by alisonrag** [comment]
Ubuntu:
```
Ubuntu LTS 18.04

DMD:
 ```
DMD64 D Compiler v2.099.0
```
DUB:
```
DUB version 1.28.0, built on Mar  6 2022
```
LDC:
```
LDC - the LLVM D compiler (1.8.0):
  based on DMD v2.078.3 and LLVM 5.0.1
  built with LDC - the LLVM D compiler (0.17.5)
  Default target: x86_64-pc-linux-gnu
```

command to compile:
```
 dub build --build=release :server
```

result of compilation (image is cli but same output for server)
![image](https://user-images.githubusercontent.com/10372732/158063770-2c3d532f-809f-4053-ae0a-763448f0ade9.png)


i will add more info, i will start the test now

**Comment by alisonrag** [comment]
using ldc2 as compiler i got this error:
`ub build --compiler=ldc2 --build=release :cli`
![image](https://user-images.githubusercontent.com/10372732/158064550-9882ce9c-7cbd-4c8b-9528-b62860a9a3bc.png)

i think this is error at the image is incompatibility between dub and ldc2 version

**Comment by alisonrag** [comment]
> @alisonrag thank you for the info. I think I have found out the point where DMD fails. However I do not know how to fix that. I have asked on the dlang forums for some help.
> 
> However, for the time being it should work when you use a newer version of LDC. I see that you currently have 1.8.0 installed which is rather old.
> 
> In comparison I am using 1.26.0, but also earlier versions such as 1.24.0 should also work:
> 
> ```
> LDC - the LLVM D compiler (1.26.0):
>   based on DMD v2.096.1 and LLVM 7.0.1
>   built with LDC - the LLVM D compiler (0.17.6)
> ```

can u send me the command that u used to install ldc?

if i'm not wrong i used the following:
`sudo apt-get install -y ldc`

**Comment by zhad3** [comment]
I am using openSuse. It seems that the Ubuntu LTS 18.04 only has LDC 1.8.0. In this case only upgrading Ubuntu will also provide higher LDC versions as I doubt that any maintainer will create a package for it.

With the help of the dlang community I have updated a dependency which now lets me compile the project with DMD but unfortunately I now see the same error as you (no rendered image). Seems like DMD is simply optimizing too aggressively or something. It seems that the output format/size is correct but nothing is being drawn...

**Comment by alisonrag** [comment]
since this seems to be a issue with compiler and not the zrenderer i will close the issue.

also i created a new vm using `Ubuntu 20.04.4 LTS`.

`apt-get install dub` don't work when u use dub command the result is this:
```
dub: symbol lookup error: dub: undefined symbol
```

so my way to make it work after install all the requirements was to use the ldc2 script to install:
`curl -fsS https://dlang.org/install.sh | bash -s ldc`
and then use this command to load dub into terminal:
` source ~/dlang/ldc-1.28.1/activate`

**Comment by alisonrag** [comment]
just to report:

using the setup above, and the command:
`dub build --compiler=ldc2 --build=release :server`

the result is:
![image](https://user-images.githubusercontent.com/10372732/158735135-4dc88b71-1a3f-4844-849d-a42f42da0bbb.png)
