### ISSUE TITLE
zrenderer dont load outfit pallete

### ISSUE THREAD

**Issue by alisonrag** [zhad3/zrenderer#24]
when using `outfit` argument zrenderer load regular body pallete instead of costume pallete

request:
```
{
    "gender": 1,
    "job": [
        "4215"
    ],
    "head": 1,
    "headPalette": 1,
    "headdir": 0,
    "headgear": [
        0,
        0,
        0
    ],
    "garment": 0,
    "bodyPalette": 3,
    "action": 0,
    "canvas": "200x200+100+150",
    "outfit": 1,
    "updated": true
}
```

result:
![image](https://user-images.githubusercontent.com/10372732/159092770-e18ddd48-c642-4541-9149-73eacc676037.png)

expected result:
![image](https://user-images.githubusercontent.com/10372732/159092731-ec3206c0-5700-4652-8d5d-4c3e717e79c8.png)

**Comment by zhad3** [comment]
Thanks for reporting. Should be fixed now:
![costume_palette](https://user-images.githubusercontent.com/6462844/162810217-81658168-3572-4eb5-8d26-77d36aabd591.png)

**Comment by alisonrag** [comment]
Thanks <3
