### ISSUE TITLE
Failed to copile on WSL

### ISSUE THREAD

**Issue by SapitoSucio** [zhad3/zrenderer#26]
Hello there, 

I activated the WSL on my win 11, I installed Debian on it.

I tried to compile but no success

![image](https://user-images.githubusercontent.com/7357354/202122843-22baada8-b6ad-4a12-aaed-939a248ea8ad.png)

**Comment by zhad3** [comment]
What version of dub are you using?

**Comment by zhad3** [comment]
Okay, that version is also pretty old.

Anyway I did some testing and this should work:  
Edit `/server/dub.selections.json`  and change the version of `openssl` to `3.2.0`.

Might fail to compile anyway if the compiler is also too old. In which case only compiling new versions of the compiler and dub will work. Or doing a cross-compilation.

**Comment by zhad3** [comment]
I have pushed new commits. Please pull them and do the following:
```shell
cd server
dub upgrade
cd ..
cd cli
dub upgrade
cd ..
dub build --compiler=ldc2 --build=release :server
```

**Comment by zhad3** [comment]
Yes, the compiler seems to old. I am using this:
```shell
$ ldc2 -version
LDC - the LLVM D compiler (1.29.0):
  based on DMD v2.099.1 and LLVM 14.0.6
```
