### ISSUE TITLE
Failed to compile on MacOS

### ISSUE THREAD

**Issue by tidre** [zhad3/zrenderer#27]
Hi,
I'm trying to compile zrenderer on MacOS but I'm having trouble trying to do it.
The installation of libpng, lua (5.1) and ldc2 has been performed but the problem still persists.

<img width="1488" alt="Captura de Tela 2023-01-13 às 07 37 51" src="https://user-images.githubusercontent.com/17967697/212301532-f86975f8-5dde-463a-97b2-189fd5918de4.png">

<img width="847" alt="Captura de Tela 2023-01-13 às 07 38 28" src="https://user-images.githubusercontent.com/17967697/212301623-9cd65ce7-5a8e-4fcf-b84e-2767381dec4c.png">

**Comment by zhad3** [comment]
Hi @tidre , OSX is currently not supported as I do not own a device.

To maybe get it to work you'd need to modify `/LuaD/dub.json` and add a new entry like this:
`"preBuildCommands-osc": ["/bin/sh \"$PACKAGE_DIR/build_clibs.sh\" \"$PACKAGE_DIR\""],`.

`/LuaD/build_clibs.sh` will most likely also be adjusted to support OSX.

The same would need to be done for https://github.com/zhad3/libpng-apng.

**Comment by tidre** [comment]
I try execute command
`dub build --force`
in project folder libpng-apng, but not locate dub.json.
<img width="733" alt="Captura de Tela 2023-01-27 às 06 40 25" src="https://user-images.githubusercontent.com/17967697/215055377-288848bb-3424-46a2-9f79-fd4627c6d2b3.png">

**Comment by zhad3** [comment]
Hi @tidre, I cannot reproduce this issue regarding dub.json missing. Make sure you are in the right folder. If you are then perhaps this is a bug with `dub`  (https://github.com/dlang/dub).

Is the docker image no option for you? https://hub.docker.com/r/zhade/zrenderer (https://github.com/zhad3/zrenderer#docker).
