### ISSUE TITLE
Erro compile in Ubuntu LTS 22.04.2

### ISSUE THREAD

**Issue by LeonardoFeriato** [zhad3/zrenderer#30]
Hi man, could you help me with compile in Ubuntu?

Follow some informations:
OS
`Ubuntu LTS 22.04.2`

DMD
`DMD64 D Compiler v2.090.1`

DUB
`DUB version 1.19.0, built on Feb 22 2020`

LDC / LDC2
`LDC - the LLVM D compiler (1.24.0):
based on DMD v2.094.1 and LLVM 11.00
built with LDC - the LLVM D compiler (1.24.0)`

OpenSSL
`OpenSSL 3.0.2 15 Mar 2022`

Command Line
`sudo dub build --compiler=ldc2 --build=release --force  : server`

![Screenshot_1](https://user-images.githubusercontent.com/37941981/235006013-8000abf6-c035-40a0-a2e3-62d4826ea3b5.png)

Output
[build_output.txt](https://github.com/zhad3/zrenderer/files/11348393/build_output.txt)

**Comment by zhad3** [comment]
Hi @LeonardoFeriato , distributions are upgrading from openssl 1.1.1 to 3.x which contain breaking api changes.
zrenderer makes use of openssl through the vibed dependency.

vibed supports openssl 3.x since version 0.9.5 with the newest (as of this writing) being 0.9.6.

To fix the linkage error you need to update vibed from 0.9.3 (current) to 0.9.6.
Modify the `zrenderer/server/dub.json` and bump the version to 0.9.6:
```patch
"dependencies": {
    "zconfig": "~>1.0",
    "libpng-apng": "~>1.0",
    "luad": {"path": "../LuaD/"},
    "zencoding:windows949": "~>1.0",
-   "vibe-d:http": "==0.9.3"
+   "vibe-d:http": "==0.9.6"
},
```
Then:
```
$ cd zrenderer/server
$ dub upgrade
$ cd ..
$ dub build --compiler=ldc2 --build=release :server
```
And it should work

**Comment by zhad3** [comment]
In the past zrenderer used to always pull the newest minor version of vibed which included openssl 3.x.
But then other (older) distributions which still use openssl 1.1.1 are broken hence I kept the older version: https://github.com/zhad3/zrenderer/commit/9eb500d7ac57556e8e720f9bdd519766465fbbd3

**Comment by LeonardoFeriato** [comment]
Did I do something wrong?

![Screenshot_2](https://user-images.githubusercontent.com/37941981/235258375-3194699f-06c6-4393-b583-92919091ba1f.png)

![Screenshot_3](https://user-images.githubusercontent.com/37941981/235258496-b6ccdc32-8259-43d4-8de5-6f570055c194.png)

**Comment by LeonardoFeriato** [comment]
I founded this [issue](https://github.com/vibe-d/vibe.d/issues/2678), according to it, we need ```dub``` version 1.30.
I had tried update my dub version without sucess. If you know how to do it, please let me know.

**Comment by LeonardoFeriato** [comment]
Hey @zhad3 I have some good news.

After some headaches, reading [this issue](https://github.com/vibe-d/vibe.d/issues/2648), and downloaded the last release and again decompress in ```root``` folder.

Finally it's compiled:
![Screenshot_6](https://user-images.githubusercontent.com/37941981/235331928-973395be-9bc5-4d5a-b87e-16774afc4a2e.png)


Is this path and executable correct? Could you please confirm that? 
![Screenshot_5](https://user-images.githubusercontent.com/37941981/235331938-91cccf2f-34df-40a6-9d62-bb023e873391.png)


If this is right. Do I just need run this? Could you pleases gimme more details?

**Comment by zhad3** [comment]
Glad to know you got it to work. The openssl version and the "DC" error are a really bad combination. It means that ubuntu updated openssl but not dub.

`zrenderer-server`  is correct. You can start it already but it won't do anything.

For zrenderer to create anything it needs the clients data as described here https://github.com/zhad3/zrenderer/blob/main/RESOURCES.md.

You then either start zrenderer and provide it the path where you extracted the data to e.g.
```sh
$ ./bin/zrenderer-server --resourcePath=resources
```
or you rename `zrenderer.example.conf` to `zrenderer.conf`  and place the path in the config file.
```
; Path to the resource directory. All resources are tried to be found within
; this directory.
; Default value: 
resourcepath=resources
```
In these example it is assumed that the resources are extracted into `zrenderer/resources/*` and the application is in `zrenderer/bin/zrenderer-server`.
Upon first starting the server it will generate an access key which you require to make api calls.

Which commands are available is described in the api-spec: https://github.com/zhad3/zrenderer#server

**Comment by LeonardoFeriato** [comment]
Thank you again for your patience and attention.
I'll do some new test and if necessary I'll open a new issue, you can closed this one.
