### ISSUE TITLE
Add documentation on how render modifiers ID's are indexed

### ISSUE THREAD

**Issue by carafelix** [zhad3/zrenderer#34]
Would be good to have a table or some sort of documentation indicating how each of the following commands are organized, for better API usage.

```
--head 
--outfit
--headgear 
--garment 
--weapon
--shield
--action 
```
Thanks in advance

**Comment by zhad3** [comment]
Could you elaborate a bit on what "how [...] commands are organized" mean?

Like, the range of available input? E.g.
| Parameter | Description |
| --- | --- |
| --head | Number between 0 and 6 |

There is no definitive input range except for jobs (player character). Each server could technically have a different amount of heads, headgears, weapons etc.

Or do you mean where to find the available input? Basically explaining how zrenderer does its look-up for data.

**Comment by carafelix** [comment]
> Or do you mean where to find the available input? Basically explaining how zrenderer does its look-up for data.

Exactly that. Thanks in advance, great work

**Comment by zhad3** [comment]
@carafelix , I've added a document that details how the inputs get resolved to sprites.

**Comment by carafelix** [comment]
Thanks! Looks clean and super easy to follow
