### ISSUE TITLE
Does it missing file on render?

### ISSUE THREAD

**Issue by LeonardoFeriato** [zhad3/zrenderer#40]
Hello, man.

Could you help me again? I use only kRO files and this happens with some jobs.
Do you have any idea what it could be?
There are no errors on console and CMD.
Really appreciate your attention.

![2024-03-05_23h12_32](https://github.com/zhad3/zrenderer/assets/37941981/89d62857-e94a-4c09-ace1-7c610aa1f1b1)
![2024-03-05_23h15_35](https://github.com/zhad3/zrenderer/assets/37941981/e6a7bdde-6f52-4159-a8d6-a7340ee1643d)

**Comment by zhad3** [comment]
I cannot reproduce the issue:
```
zrenderer --job=4124 --gender=female --action=1 --headdir=straight --head=1 --headPalette=1 --enableShadow=false
```
Please always post the full request.

![4124](https://github.com/zhad3/zrenderer/assets/6462844/337326af-a879-43d0-a00b-9c30440d2e16)

**Comment by LeonardoFeriato** [comment]
Follow using local server:
`{
    "gender": 0,
    "job": [
        "4124"
    ],
    "head": 1,
    "headPalette": 1,
    "headdir": 0,
    "headgear": [
        0,
        0,
        0
    ],
    "garment": 0,
    "bodyPalette": 0,
    "action": 1,
    "canvas": "200x200+100+150",
    "outfit": 0
}`

**Comment by zhad3** [comment]
Thank you.
The attribute `bodyPalette` seems to be the issue. A value of '0' does not always indicate the default "do nothing" value.

Have a look at the help `zrenderer -h` or https://github.com/zhad3/zrenderer?tab=readme-ov-file#cli.

It shows what the default value of each attribute is.

**Comment by zhad3** [comment]
I general I recommend to only send attributes which are intended to be changed from the default.

For example if no palette is chosen, don't send any bodyPalette in the request.

**Comment by LeonardoFeriato** [comment]
Wow, my bad.
You are correct, I got it. It works perfectly now:
Thank you very much man.
![2024-03-06_15h30_31](https://github.com/zhad3/zrenderer/assets/37941981/ecbd3639-b274-4e87-bd60-a80ce76b5643)
