### ISSUE TITLE
Sugestion Alternative Madogear

### ISSUE THREAD

**Issue by LeonardoFeriato** [zhad3/zrenderer#41]
Hello.
I would like to suggest that the alternative outfit also include the Madogear.
I have tried to apply this one without success.
![2024-03-10_14h08_43](https://github.com/zhad3/zrenderer/assets/37941981/19bb5d90-140a-4c53-aec2-353a03e3f76d)
```
{
    "gender": 0,
    "job": [
        "4279"
    ],
    "head": 21,
    "headPalette": 1,
    "headdir": 0,
    "action": 1,
    "canvas": "200x200+100+150",
    "outfit": 1
}
```
![2024-03-10_14h12_25](https://github.com/zhad3/zrenderer/assets/37941981/ad9a267e-2c75-4d51-9f4b-8793f95ed4ae)

Thanks for your great support.

**Comment by zhad3** [comment]
Do you know how the alternative sprite works in-game? (I don't play Ragnarok anymore) I had a hard time looking up information about it. I found a YouTube video in korean that shows how he buys and uses the item "Emergency Mado Gear(Reinforcement Suit)" https://ratemyserver.net/index.php?page=re_item_db&item_id=100158.

The item applies some sort of effect on the player, but does not in fact changes the job (as is done for example the Tuxedo/Wedding Dress).

There also seems to be multiple madogear jobs and supposedly alternative sprites.

For example there is:
| JobId | Name |
| --- | --- |
| 4086 | 마도기어 |
| 4087 | 마도기어 |
| 4112 | 마도기어 |
| 4297 | MEISTER_MADOGEAR1 |

And there are the following alternative sprites:
`마도아머`, `MEISTER_MADOGEAR2`.

For now I would guess that if your job is `마도기어` then the alternative sprite would be `마도아머` and respectively if your job is `MEISTER_MADOGEAR1` then your alternative sprite would be `MEISTER_MADOGEAR2`. Again, I do not know how it actually works in the official client.

**Comment by LeonardoFeriato** [comment]
> Do you know how the alternative sprite works in-game? (I don't play Ragnarok anymore) I had a hard time looking up information about it. I found a YouTube video in korean that shows how he buys and uses the item "Emergency Mado Gear(Reinforcement Suit)" https://ratemyserver.net/index.php?page=re_item_db&item_id=100158.
> 
> The item applies some sort of effect on the player, but does not in fact changes the job (as is done for example the Tuxedo/Wedding Dress).
This is correct, it is using this item to apply the new Madogear. Internally in the files I can't say how the script for this item will work, but as far as I know it is only using this item.

Actually, the way other jobs traditionally are, it won't work for this one. I had also checked the files that `resolver.d` uses before opening this issue and I believe that this will have to be a new implementation as Companion (e.g. Falcon).

I've found inconsistencies in the game files, certain costumes and items don't follow the old standard.

**Comment by zhad3** [comment]
Please checkout version 1.4.0.

You can now specify a new argument: `--madogearType={robot,suit}`. API usage is respectively: `"madogearType": {0,2}`.

```json
{
    "gender": 0,
    "job": [
        "4279"
    ],
    "head": 21,
    "headPalette": 1,
    "headdir": 0,
    "action": 1,
    "canvas": "200x200+100+150",
    "madogearType": 2
}
```
Results in: 
![1-0](https://github.com/zhad3/zrenderer/assets/6462844/689e2665-a496-443c-b639-0fc1171eebc2)

**Comment by LeonardoFeriato** [comment]
Awesome dude!
I'll try it out, thank you very much.
