### ISSUE TITLE
Rendering only player head

### ISSUE THREAD

**Issue by t-kky** [zhad3/zrenderer#42]
Is it currently possible to render only the head of player? If not, this is something that would be a nice addition!

**Comment by zhad3** [comment]
I thought about it but ultimately the only use-case I can see is if you wish to render something like a headgear preview.

It does clash with what the purpose of zrenderer: "Render sprites as the original client as images"

**Comment by t-kky** [comment]
Player heads are rendered in the guild window. Being able to render heads would allow websites, launchers, etc, to display a preview of the character head in a similar way (where a full sprite might take up too much space).

**Comment by zhad3** [comment]
Please check out version 1.4.0. I've added an extra 'none' value to the `job`  argument. When passed it will only render the player head and with headgears and nothing else.

Example: `./zrenderer --job=none --action=7 --head=18 --headgear=311 --headPalette=3 --gender=female`

Result: ![Head](https://github.com/zhad3/zrenderer/raw/main/examples/none_7.png)

zrenderer wasn't designed to be able to render individual segments but always a fully composited player sprite. In that sense I have included what is basically an "empty" body sprite (act+spr) which is used.
