### ISSUE TITLE
Failing to Run/Build on Windows

### ISSUE THREAD

**Issue by 4reezy** [zhad3/zrenderer#43]
OS: Windows 11
Visual Studio 2019.

Everytime I run zserver, I'm getting as far as to get a generated localhost link, but when clicking said link, I'm redirected to a 404.
Also, a error message pops up in the terminal/log ?
![image](https://github.com/zhad3/zrenderer/assets/125038794/74f11e00-bfa1-47cf-82d2-4a8f56a68a8b)

![1885](https://github.com/zhad3/zrenderer/assets/125038794/4378414b-3c6a-4a64-bdd8-6e421a10d692)

When running zrenderer, an Output folder is generated but nothing ever comes out. I even tried git pull method and it seemingly got further but ultimately keep running into the same issue.

**Comment by LeonardoFeriato** [comment]
Hey man.

When you run server, your localhost port keeps waiting for some REST post requests. Which means you need to use some app like PostMan to send a post request to your localhost:11011. Just opening it in your browser doesn't work.

Like this:
![2024-03-16_22h24_11](https://github.com/zhad3/zrenderer/assets/37941981/1dbd65fc-5456-49fe-8771-71684a82d2a8)

Take a look at:
Method: https://z0q.neocities.org/ragnarok-online-tools/zrenderer/api/#render 
Body Request: https://z0q.neocities.org/ragnarok-online-tools/zrenderer/api/#RenderRequest

Your token will be in file `accesstokens.conf`

**Comment by 4reezy** [comment]
Dowloaded the latest version of Postman and replicated the same link with my token instead and still running into issues.
![image](https://github.com/zhad3/zrenderer/assets/125038794/25f43d55-e9a2-4085-8947-ad8bca363a90)

**Comment by zhad3** [comment]
As Leonardo already pointed out. There is no graphical interface and there won't be one implemented in this repository.

Someone else made a website which uses zrenderer in the backend and can be found here: https://github.com/alisonrag/vue-visual-simulator.
The website in the repo is down but a new one is hosted at https://visualrag.ragnarok.wiki/.
AFAIK it only contains bRO content though.

**Comment by alisonrag** [comment]
> Dowloaded the latest version of Postman and replicated the same link with my token instead and still running into issues. ![image](https://private-user-images.githubusercontent.com/125038794/313451907-25f43d55-e9a2-4085-8947-ad8bca363a90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MTQ3NjQsIm5iZiI6MTcxMDcxNDQ2NCwicGF0aCI6Ii8xMjUwMzg3OTQvMzEzNDUxOTA3LTI1ZjQzZDU1LWU5YTItNDA4NS04OTQ3LWFkOGJjYTM2M2E5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QyMjI3NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTNmNDVmNDg4YjBhYTc4YzBiZTM4OTljYjJhN2UzMmZmZjA1NmNlODYwN2MxMTA2MWI1MzM5MTViNWY3YjBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RnT76SsYqesYxi1hvWQzPZ7BGP4knE-Zplg5BS1o-mg)

you sent a null body, you need to fill what do you want to render in a JSON
you can see some examples in [LeonardoFeriato](https://github.com/LeonardoFeriato) reply

**Comment by zhad3** [comment]
@4reezy if you still need help on how to use the server API please create a new discussion topic at https://github.com/zhad3/zrenderer/discussions.

I'll close this issue as "invalid".
